### ISSUE TITLE
Certificate Progress only updates if you've watched the whole video

### ISSUE THREAD

**Issue by sdras** [netlify/explorers#375]
We should probably show some progress for partial completion
<img width="1145" alt="CleanShot 2020-11-17 at 20 12 03@2x" src="https://user-images.githubusercontent.com/2281088/99478293-61fbb200-2911-11eb-9dc5-41a3e3869c7c.png">

**Comment by tzmanics** [comment]
from mob job discussion today: 

- 👉 let's do this one! easy but less accurate way (from @jlengstorf's 🧠): we already calculate the mission progress, so we can 
  - the certificate completion graph total will be 1 and the certificate progress amount will be the total mission video completion sum * 0.33
(I did this wrong, plz halp @jlengstorf 👆)

- hard but more accurate way: 
  - sort missions by most completed (highest (videos watched/total videos)) and add their total of videos (missionStageCount)
  - add the total videos watched for those 3 missions (missionCompletedStages)
  - the graph total will be missionStageCount and progress would be missionCompletedStages divided by missionStageCount

- other goals + accreditation will remove mission certificates (postcard from space at the end of mission, unlock a constellation (that could also trigger postcard from space w the constellation), want everyone to do serverless functions then have it be you get a serverless function swag item sent to you)

**Comment by jlengstorf** [comment]
lol @tzmanics 

math breakdown:

1. we already have the list of missions and percentage complete (that's what we're showing on the main area of the user page)
2. we can sort the missions by "most complete" and take a subset of the 3 most complete missions
3. for each mission, we'll multiply `1 / 3 * missionCompleteness`
4. we can add those three values together to get a certificate progress as a value between 0 and 1, which we can display as a percentage

this should let us avoid adding more heavy logic and actually provides a pretty accurate progress value since each mission can only affect 1/3 of your certificate progress

**Comment by jlengstorf** [comment]
I don't know how this happened, but the code from #437 got merged into main as part of #438. I assume I pulled a branch incorrectly

either way, this has been merged and fixed
<img width="2121" alt="Screen Shot 2021-01-22 at 9 38 35 AM" src="https://user-images.githubusercontent.com/163561/105525386-e104c200-5c95-11eb-9ed7-cec0b2a62689.png">
