### ISSUE TITLE
profile page footer has a rogue top margin

### ISSUE THREAD

**Issue by jlengstorf** [netlify/explorers#427]
looks like the footer content is escaping its container

<img width="1305" alt="Screen Shot 2020-11-23 at 2 58 07 PM" src="https://user-images.githubusercontent.com/163561/100024818-60603d00-2d9c-11eb-85b6-6308c96d2be1.png">

**Comment by thsnyzkn** [comment]
Hello,
I guess, the margin-top value within the div which has the class name of profile page causes this problem.
Once, I gave the same value as padding-top instead of margin-top the rogue top margin is disappeared and the footer is turned into as following:

![Screen Shot 2020-12-12 at 20 50 43](https://user-images.githubusercontent.com/12461397/101991263-8e121500-3cbc-11eb-9f98-8418f6268ba1.png)
But, I wouldn't know that this could be the ideal solution and there could be any other complications regarding with this modification.
