### ISSUE TITLE
Set up new tables in Hasura to support the rewards flow

### ISSUE THREAD

**Issue by philhawksworth** [netlify/explorers#475]
- [x] Create the `achievements` table in Hasura
- [x] Create `rewards` table in Hasura
- [x] Create relationships between `achievements` and `rewards` tables so we can query in GraphQL
- [x] Register a webhook in Hasura to run whenever the `activity` table gets new data (ref #471)

**Comment by tzmanics** [comment]
I _believe_ the relationship between achievements and rewards is solved using a many to many relationship and making a bridge table ([see the Hasura docs](https://hasura.io/docs/1.0/graphql/core/guides/data-modelling/many-to-many.html)). using that approach I was able to query it successfully:
<img width="917" alt="Screen Shot 2021-02-09 at 5 11 08 PM" src="https://user-images.githubusercontent.com/3611928/107441639-8d9eca80-6b03-11eb-8e49-c52fe107eaa8.png">

This was my thought process:
- Scenario 1: if you complete a mission, you get a sticker pack
- Scenario 2: if you complete 2 missions, you get a t-shirt and a sticker pack
- Scenario 3: if you watch the intro video you get a sticker pack and a book

```
rewards = [
  { "name": "tshirt" },
  { "name": "stickers" },
  { "name": "book" }
]
achievements = [
  { "name": "mission complete" },
  { "name": "two missions complete" },
  { "name": "intro video watched" }
]
achievement_rewards = [
  { "achievement": "mission complete",
    "reward": ["stickers"] }, // scenario 1
  { "achievement": "2 missions complete",
    "reward": ["tshirt", "stickers"] }, // scenario 2
  { "achievement": "intro video watched",
    "reward": ["stickers", "book"] }, // scenario 3
]
```
as far as process:

scenario: you make an achievement and you want to add a reward
- if reward exists: add achievement_id and reward_id to achievement-reward table
- reward doesn’t exist: create reward in reward table then do :point_up:

**Comment by tzmanics** [comment]
Ok, i deleted my last long comment to avoid any confusion.

The `rewards` table is now set up correctly (thank you @jlengstorf) so that it has a column for `achievement_id` that has an object relationship to `id` in the `achievements` table.

The `achievements` table never needs to know any information about rewards so no new columns were added but it's `id` now has an array relationship to `achievement_id` in the `rewards` table.

Next steps:
- work on #468 to write to the achievement table
- make a new event trigger ([like the jamstack-exploreres-check-achievement one](https://destined-bobcat-42.hasura.app/console/events/data/jamstack-explorers-check-achievement/modify)) that will grab the `achievement_id` and write to the `rewards` table.

<img width="949" alt="Screen Shot 2021-02-10 at 12 28 55 PM" src="https://user-images.githubusercontent.com/3611928/107547647-ace93680-6b9b-11eb-823d-ea69a51e15aa.png">
